# Generated by Django 4.2.7 on 2025-10-06 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícono')),
                ('color', models.CharField(default='#90AF90', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Kg (S/.)')),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Kg Disponible')),
                ('available_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Disponibles')),
                ('producer_name', models.CharField(max_length=200, verbose_name='Nombre del Productor')),
                ('producer_phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono del Productor')),
                ('community', models.CharField(max_length=100, verbose_name='Comunidad')),
                ('region', models.CharField(default='Pasco', max_length=100, verbose_name='Región')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendido'), ('reserved', 'Reservado'), ('pending', 'Pendiente')], default='available', max_length=20, verbose_name='Estado')),
                ('quality', models.CharField(choices=[('premium', 'Premium'), ('standard', 'Estándar'), ('basic', 'Básico')], default='standard', max_length=20, verbose_name='Calidad')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen del Producto')),
                ('harvest_date', models.DateField(verbose_name='Fecha de Cosecha')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('is_organic', models.BooleanField(default=False, verbose_name='Es Orgánico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
